FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './results' # Testing files saving path

DATASET:
  SMPL_PATH: './deps/smpl'
  TRANSFORM_PATH: './deps/transforms/'
  WORD_VERTILIZER_PATH: './deps/glove/'
  UNIMOCAP:
    ROOT: './datasets/UniMocap' # KIT directory
    SPLIT_ROOT: './datasets/UniMocap' # KIT splits directory
  KIT:
    ROOT: './datasets/kit-ml' # KIT directory
    SPLIT_ROOT: './datasets/kit-ml' # KIT splits directory
  HUMANML3D:
    ROOT: './datasets/humanml3d' # HumanML3D directory
    SPLIT_ROOT: './datasets/humanml3d' # HumanML3D splits directory
  HUMANACT12:
    ROOT: ./datasets/HumanAct12Poses
    SPLIT_ROOT: ./datasets/HumanAct12Poses
  UESTC:
    ROOT: ./datasets/uestc
    SPLIT_ROOT: ./datasets/uestc
  AMASS:
    DB_ROOT: /apdcephfs/share_1227775/shingxchen/uicap/data/vibe_db
  MOTIONX:
    ROOT: ./datasets/Motion-X
    SPLIT_ROOT: ./datasets/Motion-X/split
    SEMANTIC_TEXT_ROOT: ./datasets/Motion-X/texts/semantic_texts
    FACE_TEXT_ROOT: ./datasets/Motion-X/texts/face_texts


model:
  bert_path: './deps/distilbert-base-uncased' # bert model path for all text encoders
  clip_path: './deps/clip-vit-large-patch14' # bert model path for all text encoders
  t2m_path: './deps/t2m/'

  humanact12_rec_path: './deps/actionrecognition'
  uestc_rec_path: './deps/actionrecognition'

RENDER:
  BLENDER_PATH: '/apdcephfs/share_1227775/mingzhenzhu/jiangbiao/libs/blender-2.93.2-linux-x64/blender'
  FACES_PATH: '/apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/deps/smplh/smplh.faces'
  FOLDER: ./animations
