motiondecoder:
  name: actor_decoder
  target: mld.models.architectures.temos.motiondecoder.actor.ActorAgnosticDecoder
  params:
    latent_dim: ${model.latent_dim}
    ff_size: ${model.ff_size}
    num_layers: ${model.num_layers}
    num_head: ${model.num_head}
    droupout: ${model.dropout}
    activation: ${model.activation}
    nfeats: ${DATASET.NFEATS}