motionencoder:
  name: actor_encoder
  target: tma.models.architectures.temos.motionencoder.actor.ActorAgnosticEncoder
  params:
    latent_dim: ${model.latent_dim}
    vae: ${model.vae}
    ff_size: ${model.ff_size}
    num_layers: ${model.num_layers}
    num_head: ${model.num_head}
    droupout: ${model.dropout}
    activation: ${model.activation}
    nfeats: ${DATASET.NFEATS}